"""tutaj wiadomosc

Revision ID: b74656e462b6
Revises: d9928dee534a
Create Date: 2023-04-20 19:02:42.979244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74656e462b6'
down_revision = 'd9928dee534a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
